name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub_
      uses: docker/login-action@v1
      with:
        username: steflight
        password: St697718256!!!

    - name: Build and push Docker image
      run: |
        docker-compose build
        docker tag my-static-page:latest my-dockerhub-username/my-static-page:latest
        docker push my-dockerhub-username/my-static-page:latest

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
